version: 1
policies:
  Token-Permissions:
      score: 10
      mode: enforced
  Branch-Protection:
      score: 10
      mode: enforced
  Code-Review:
      score: 10
      mode: enforced
  Pinned-Dependencies:
      score: 10
      mode: enforced
  Security-Policy:
      score: 10
      mode: enforced
  SAST:
      score: 10
      mode: enforced
  Contributors:
      score: 10
      mode: enforced
  Packaging:
      score: 10
      mode: enforced
  Binary-Artifacts:
      score: 10
      mode: enforced
  Signed-Releases:
      score: 10
      mode: enforced
  Dependency-Update-Tool:
      score: 10
      mode: enforced
  Fuzzing:
      score: 10
      mode: enforced
  CII-Best-Practices:
      score: 10
      mode: enforced
  Vulnerabilities:
      score: 10
      mode: enforced
  CI-Tests:
      score: 10
      mode: enforced
  Maintained:
      score: 10
      mode: enforced
